stages:
  - master
  - production

check_master:
  stage: master
  script:
    - bash test/bash_unit test/test_url-splitting.sh
  tags:
    - shell
  except:
    - production

merge_to_production:
  stage: production
  script:
    - git pull origin production
    - git push master HEAD:production
  tags:
    - shell
  when: on_success
